Map: Display Zero Case Growth in Grey
PublicHealthEngland/coronavirus-dashboard pull request #472
Opened 2021-08-30 09:19 UTC by Aurorum

Ensures that the box is grey rather than green when there has not been a change in coronavirus cases.

**Testing instructions:**

1. Go to `/details/interactive-map/cases`
2. Either manually force an area to have zero case growth, or find an area that actually has not had a change in COVID cases (Oxfordshire is currently one) 
3. Verify that the colour is grey (the shade is taken from the homepage) instead of green

| Before                                                                                                                                                                | After                                                                                                                                                                 |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="337" alt="Screenshot 2021-08-30 at 10 08 23" src="https://user-images.githubusercontent.com/43215253/131316479-d8655922-90cb-45a8-b58b-9b3a3476146c.png"> | <img width="336" alt="Screenshot 2021-08-30 at 10 08 28" src="https://user-images.githubusercontent.com/43215253/131316488-48ecfca2-c05a-42dc-b70a-02b96ea55375.png"> |

Fixes #464

@xenatisch apologies - I recognise that you were assigned to the issue, but I couldn't find a branch for this and I assume it wasn't already being worked on because it's a Bank Holiday? Would appreciate if you could review, thanks! :)

2021-08-30 23:00 UTC, xenatisch requested changes
Thank you for this. This part is pretty embedded in our code, so you must have spent a bit of time going through the maze. 

Just a tiny change needed, and we'll be good to go.

2021-08-30 23:00 UTC, xenatisch commented on src/components/Map/Map.styles.js
> +                background-color: rgb(235,233,231.2);
Missing a comma here, though I don't think we need to set alpha for this one. It's pretty light.

2021-08-30 23:15 UTC, Aurorum commented on src/components/Map/Map.styles.js
> +                background-color: rgb(235,233,231.2);
Ah, oops, good spot! I've removed it now. Thanks for taking a look! :)

2021-08-31 08:40 UTC, xenatisch approved these changes

2021-08-31 08:50 UTC, merged